// @generated by `ruskel-snapshot`; do not edit.
//
// Package: mrpc
// Publish: crates.io
// Declared features: default, serde
// Workspace dependencies: none
// Workspace dependents: none

//! MessagePack-RPC implementation in Rust.
//!
//! Provides asynchronous RPC servers and clients over TCP and Unix domain
//! sockets. Implements the full MessagePack-RPC specification.
//!
//! Both servers and clients can handle incoming RPC messages, enabling
//! bidirectional communication.
//!
//! To implement a server:
//! 1. Implement the `Connection` trait
//! 2. Create a `Server` with the service
//! 3. Call `server.tcp(addr)` or `server.unix(path)`
//! 4. Call `server.run()`
//!
//! To implement a client:
//! 1. Implement the `Connection` trait
//! 2. Create a `Client` via `Client::connect_tcp(addr, service)` or
//!    `Client::connect_unix(path, service)`
//! 3. Use `client.send_request()` or `client.send_notification()`

use std::{
    fmt::{Debug, Display},
    io::{Read, Write},
    marker::Unpin,
    net::SocketAddr,
    path::Path,
    pin::Pin,
};

use rmpv::Value;
pub use rmpv::Value;
use tokio::{
    io::{DuplexStream, async_read::AsyncRead, async_write::AsyncWrite},
    sync::watch::Sender,
    task::JoinError,
};
/// A single Connection in an RPC server or client. For server connections, a
/// new instance of the Connection is created for each incoming connection. For
/// clients, a single instance is used for the lifetime of the connection.
///
/// As a convenience for clients that don't need to handle requests or
/// responses, the `Connection` trait is implemented for `()`, and the `Client`
/// type exposes `send_request` and `send_notification` directly.
///
/// Use the `#[async_trait]` attribute from the `async_trait` crate when
/// implementing this trait to support async methods.
#[async_trait]
pub trait Connection: 'static + Send + Sync {
    /// Called after a connection is initiated, either by a `Client` connecting
    /// outbound, or an incoming connection on a listening `Server`.
    async fn connected(&self, _client: RpcSender) -> crate::Result<()> {}

    /// Handles an incoming RPC notification.
    ///
    /// By default, logs a warning about the unhandled notification.
    async fn handle_notification(
        &self,
        _client: RpcSender,
        method: &str,
        params: Vec<Value>,
    ) -> crate::Result<()> {
    }

    /// Handles an incoming RPC request.
    ///
    /// By default, returns a `MethodNotFound` service error.
    async fn handle_request(
        &self,
        _client: RpcSender,
        method: &str,
        params: Vec<Value>,
    ) -> crate::Result<Value> {
    }
}

impl Connection for () {}

/// A trait for creating connections.
///
/// `ConnectionMaker` provides a generic way to create objects that implement
/// the `Connection` trait. It is automatically implemented for any type that
/// implements both `Connection` and `Default`.
///
/// The ConnectionMaker is used to create a new Connection object for each
/// incoming connection.
pub trait ConnectionMaker<T>: Send + Sync
where
    T: Connection, {
    /// Creates a new connection instance.
    fn make_connection(&self) -> T;
}

impl<T> ConnectionMaker<T> for T where T: Connection + Default {}

/// A listener that yields bidirectional streams.
#[async_trait]
pub trait Listener: 'static + Send + Sync {
    /// The stream type produced by accepting a connection.
    type Stream: 'static + AsyncRead + AsyncWrite + Send + Unpin;
    /// Accept the next connection.
    async fn accept(&self) -> crate::Result<<Self as Listener>::Stream>;
}

/// RPC client for connecting to a server over TCP or Unix domain sockets.
#[derive(Debug)]
pub struct Client {/* private fields */}

impl Client {
    /// Shuts down the client and waits for the handler task to complete.
    pub async fn close(self) -> crate::Result<()>;

    /// Creates a new client connected to a TCP address.
    pub async fn connect_tcp<T>(addr: &str, service: T) -> crate::Result<Self>
    where
        T: Connection;

    /// Creates a new client connected to a Unix domain socket.
    pub async fn connect_unix<P, T>(path: P, service: T) -> crate::Result<Self>
    where
        P: AsRef<Path>,
        T: Connection;

    /// Creates a new client from any bidirectional stream.
    pub async fn from_stream<S, T>(stream: S, service: T) -> crate::Result<Self>
    where
        S: 'static + AsyncRead + AsyncWrite + Send + Unpin,
        T: Connection;

    /// Waits for the client handler task to complete.
    pub async fn join(self) -> crate::Result<()>;

    /// Sends an RPC notification to the server. Convenience method for
    /// `RpcSender::send_notification`.
    pub async fn send_notification(&self, method: &str, params: &[Value]) -> crate::Result<()>;

    /// Sends an RPC request to the server. Convenience method for
    /// `RpcSender::send_request`.
    pub async fn send_request(&self, method: &str, params: &[Value]) -> crate::Result<Value>;

    /// Returns a sender for issuing RPC requests and notifications.
    pub fn sender(&self) -> RpcSender;

    /// Signals the client to stop processing messages and close the connection.
    pub fn shutdown(&self);

    /// Queues an RPC request and returns a handle with the assigned msgid.
    pub async fn start_request(
        &self,
        method: &str,
        params: &[Value],
    ) -> crate::Result<RequestHandle>;
}

impl Drop for Client {}

/// Shared runtime state for a live connection handler.
///
/// This bundles the handler task inputs so transport code can start a client
/// or accepted server connection without depending on lower-level connection
/// plumbing types.
pub struct ConnectionRuntime<S, T: Connection>
where
    S: 'static + AsyncRead + AsyncWrite + Send + Unpin, {/* private fields */}

impl<S, T> ConnectionRuntime<S, T>
where
    S: 'static + AsyncRead + AsyncWrite + Send + Unpin,
    T: Connection,
{
    /// Creates a runtime from a bidirectional stream and connection service.
    pub fn new(stream: S, service: T) -> Self;

    /// Runs the connection handler until the stream closes or shutdown is
    /// requested.
    pub async fn run(self) -> crate::Result<()>;

    /// Returns a sender for issuing RPC requests and notifications.
    pub fn sender(&self) -> RpcSender;

    /// Returns a shutdown handle for the background reader task.
    pub fn shutdown_sender(&self) -> Sender<bool>;
}

/// Represents the different types of RPC messages: requests, responses, and
/// notifications.
#[derive(Clone, Debug, PartialEq)]
pub enum Message {
    /// An RPC request.
    Request(Request),
    /// An RPC response.
    Response(Response),
    /// An RPC notification.
    Notification(Notification),
}

impl Message {
    /// Reads and decodes a message from MessagePack format using the given
    /// reader.
    pub fn decode<R: Read>(reader: &mut R) -> crate::Result<Self>;

    /// Encodes the message to MessagePack format and writes it to the given
    /// writer.
    pub fn encode<W: Write>(&self, writer: &mut W) -> crate::Result<()>;

    /// Creates a Message from a MessagePack-RPC compatible Value.
    pub fn from_value(value: Value) -> crate::Result<Self>;

    /// Converts the message to a MessagePack-RPC compatible Value.
    pub fn to_value(&self) -> Value;
}

/// An RPC notification message containing a method name and parameters.
#[derive(Clone, Debug, PartialEq)]
pub struct Notification {
    /// The method name to invoke.
    pub method: String,
    /// Arguments to pass to the method.
    pub params: Vec<Value>,
}

/// Errors indicating a violation of the MessagePack-RPC protocol or message
/// framing.
#[derive(Debug, Display, std::error::Error)]
pub enum ProtocolError {
    /// A service value did not encode as a single-tag serde enum.
    #[error("expected a serde-tagged service enum")]
    InvalidServiceEnum,
    /// Received a value that was not a top-level MessagePack-RPC message array.
    #[error("Invalid message format")]
    InvalidMessageFormat,
    /// Received an empty top-level MessagePack-RPC message array.
    #[error("Empty message array")]
    EmptyMessageArray,
    /// Received a message with an invalid type tag.
    #[error("Invalid message type: {0}")]
    InvalidMessageType(u64),
    /// Received a message body with an unexpected number of fields.
    #[error("Invalid {kind} message length")]
    InvalidMessageLength {
        /// The message kind whose field count was invalid.
        kind: &'static str,
    },
    /// Received a message field that did not have the expected shape or type.
    #[error("Invalid {kind} {field}")]
    InvalidMessageField {
        /// The message kind or decode context.
        kind: &'static str,
        /// The field whose value was invalid.
        field: &'static str,
    },
    /// A full MessagePack value exceeded the configured nesting limit.
    #[error("Depth limit exceeded")]
    DepthLimitExceeded,
    /// A caller requested a bound socket address before any listener was
    /// configured.
    #[error("No listener configured")]
    ListenerNotConfigured,
    /// A configured listener does not expose a bound `SocketAddr`.
    #[error("Listener has no SocketAddr")]
    MissingSocketAddr,
    /// A MessagePack-RPC single-parameter helper received the wrong arity.
    #[error("Expected exactly one parameter")]
    ExpectedSingleParameter,
    /// A single-consumer resource was taken more than once.
    #[error("Resource already taken: {resource}")]
    ResourceAlreadyTaken {
        /// The resource that was already taken.
        resource: &'static str,
    },
    /// A background task failed before completing normally.
    #[error("Task '{task}' failed: {source}")]
    TaskFailed {
        /// The task that failed.
        task: &'static str,
        /// The underlying join failure.
        #[source]
        source: JoinError,
    },
    /// Received a response for a request id that has no pending waiter.
    #[error("Unexpected response id: {id}")]
    UnexpectedResponse {
        /// The request id.
        id: u32,
    },
    /// Received a message that does not match the expected structure.
    #[error("Malformed message: {0}")]
    MalformedMessage(String),
}

impl From<&str> for ProtocolError {}

impl From<String> for ProtocolError {}

/// An RPC request message containing an ID, method name, and parameters.
#[derive(Clone, Debug, PartialEq)]
pub struct Request {
    /// Unique identifier for matching responses.
    pub id: u32,
    /// The method name to invoke.
    pub method: String,
    /// Arguments to pass to the method.
    pub params: Vec<Value>,
}

/// Handle to an in-flight RPC request.
///
/// Exposes the msgpack-RPC [`msgid`](Self::id) assigned to the request as
/// soon as it is queued, so callers can reference it in out-of-band
/// protocol messages (such as application-level cancellation) before the
/// response arrives. The response is retrieved via
/// [`response`](Self::response).
#[derive(Debug)]
pub struct RequestHandle {/* private fields */}

impl RequestHandle {
    /// Returns the msgpack-RPC `msgid` of the request.
    pub fn id(&self) -> u32;

    /// Awaits the response. Consumes the handle.
    pub async fn response(self) -> crate::Result<Value>;
}

/// An RPC response message containing an ID and either a result or an error.
#[derive(Clone, Debug, PartialEq)]
pub struct Response {
    /// Matches the request ID this is responding to.
    pub id: u32,
    /// The result value or error value.
    pub result: Result<Value, Value>,
}

/// A type alias for `Result` with [`RpcError`] as the error type.
pub type Result<T> = Result<T, RpcError>;

/// Errors that can occur during RPC operations.
#[derive(Debug, Display, std::error::Error)]
pub enum RpcError {
    /// Error occurred during I/O operations.
    #[error("I/O error: {0}")]
    Io(std::io::Error),
    /// Error occurred while trying to establish a connection.
    #[error("Connection failed: {source}")]
    Connect {
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// Error occurred during MessagePack serialization.
    #[error("Serialization error: {0}")]
    Serialization(rmpv::encode::Error),
    /// Error occurred during MessagePack deserialization.
    #[error("Deserialization error: {0}")]
    Deserialization(rmpv::decode::Error),
    /// Error related to the MessagePack-RPC protocol.
    #[error(transparent)]
    Protocol(ProtocolError),
    /// Error returned by the RPC service implementation.
    #[error("Service error: {0}")]
    Service(ServiceError),
    /// The connection was closed.
    #[error("Connection disconnected")]
    Disconnect {
        /// Underlying I/O error, when available.
        #[source]
        source: Option<std::io::Error>,
    },
}

impl From<ProtocolError> for RpcError {}

impl From<rmpv::decode::Error> for RpcError {}

impl From<rmpv::encode::Error> for RpcError {}

impl From<std::io::Error> for RpcError {}

/// The interface for sending RPC requests and notifications.
#[derive(Clone, Debug)]
pub struct RpcSender {/* private fields */}

impl RpcSender {
    /// Sends an RPC notification without waiting for a response.
    pub async fn send_notification(&self, method: &str, params: &[Value]) -> crate::Result<()>;

    /// Sends an RPC request and waits for the response. Equivalent to
    /// [`start_request`](Self::start_request) followed by awaiting the
    /// returned handle; the id is not exposed.
    pub async fn send_request(&self, method: &str, params: &[Value]) -> crate::Result<Value>;

    /// Queues an RPC request and returns a [`RequestHandle`] that carries
    /// the assigned `msgid` and yields the response when awaited. The
    /// method returns as soon as the request is accepted by the channel,
    /// so callers see the id before the response arrives.
    pub async fn start_request(
        &self,
        method: &str,
        params: &[Value],
    ) -> crate::Result<RequestHandle>;
}

/// RPC server that can listen on TCP or Unix domain sockets.
///
/// The connection type must implement [`Connection`]. A new connection instance
/// is created for each accepted stream.
pub struct Server<T>
where
    T: Connection, {/* private fields */}

impl<T> Server<T>
where
    T: Connection + Default,
{
    /// Creates a new server from a listener using `T::default` for each
    /// connection.
    pub fn from_listener<L>(listener: L) -> crate::Result<Self>
    where
        L: Listener;
}

impl<T> Server<T>
where
    T: Connection,
{
    /// Helper method to create a Server from a closure
    pub fn from_fn<F>(f: F) -> Self
    where
        F: 'static + Fn() -> T + Send + Sync;

    /// Creates a new Server with the given ConnectionMaker.
    pub fn from_maker<M>(maker: M) -> Self
    where
        M: 'static + ConnectionMaker<T> + Send + Sync;

    /// Returns the bound address of the server. Only valid for TCP listeners
    /// that have already been bound, otherwise returns an error.
    pub fn local_addr(&self) -> crate::Result<SocketAddr>;

    /// Starts the server and begins accepting connections.
    pub async fn run(self) -> crate::Result<()>;

    /// Starts the server and returns a handle for lifecycle control.
    pub async fn spawn(self) -> crate::Result<ServerHandle>;

    /// Configures the server to listen on a TCP address.
    pub async fn tcp(self, addr: &str) -> crate::Result<Self>;

    /// Configures the server to listen on a Unix domain socket.
    pub async fn unix<P: AsRef<Path>>(self, path: P) -> crate::Result<Self>;

    /// Configures the server to accept connections from a custom listener.
    pub fn with_listener<L>(self, listener: L) -> crate::Result<Self>
    where
        L: Listener;
}

/// A handle for controlling a running server.
#[derive(Debug)]
pub struct ServerHandle {/* private fields */}

impl ServerHandle {
    /// Waits for the server to stop and returns any error.
    pub async fn join(self) -> crate::Result<()>;

    /// Returns the bound TCP address of the server.
    ///
    /// This is only valid for TCP listeners; Unix listeners do not have a
    /// `SocketAddr`.
    pub fn local_addr(&self) -> crate::Result<SocketAddr>;

    /// Signals the server to stop accepting new connections.
    pub fn shutdown(&self);
}

/// An error that occurred during the execution of an RPC service method.
///
/// It consists of a name, which identifies the type of error, and a value,
/// which can contain additional error details. This error type is used to
/// convey service-specific errors back to the client. When sent over the RPC
/// protocol, this error will be serialized into a map with "name" and "value"
/// keys.
#[derive(Debug, Display, std::error::Error)]
pub struct ServiceError {
    /// The error type name.
    pub name: String,
    /// Additional error data.
    pub value: Value,
}

impl ServiceError {
    /// Creates a standard service error for an unknown RPC method.
    pub fn method_not_found(method: &str) -> Self;
}

impl From<ServiceError> for Value {}

impl TryFrom<Value> for ServiceError {
    type Error = Value;
}

/// Create a pair of connected in-memory streams.
pub fn duplex(buffer_size: usize) -> (DuplexStream, DuplexStream);
