// @generated by `ruskel-snapshot`; do not edit.

pub mod mrpc {
    //! MessagePack-RPC implementation in Rust.
    //!
    //! Provides asynchronous RPC servers and clients over TCP and Unix domain
    //! sockets. Implements the full MessagePack-RPC specification.
    //!
    //! Both servers and clients can handle incoming RPC messages, enabling
    //! bidirectional communication.
    //!
    //! To implement a server:
    //! 1. Implement the `Connection` trait
    //! 2. Create a `Server` with the service
    //! 3. Call `server.tcp(addr)` or `server.unix(path)`
    //! 4. Call `server.run()`
    //!
    //! To implement a client:
    //! 1. Implement the `Connection` trait
    //! 2. Create a `Client` via `Client::connect_tcp(addr, service)` or
    //!    `Client::connect_unix(path, service)`
    //! 3. Use `client.send_request()` or `client.send_notification()`

    /// Errors indicating a violation of the MessagePack-RPC protocol or message
    /// framing.
    pub enum ProtocolError {
        #[error("expected a serde-tagged service enum")]
        /// A service value did not encode as a single-tag serde enum.
        InvalidServiceEnum,
        #[error("Invalid message format")]
        /// Received a value that was not a top-level MessagePack-RPC message array.
        InvalidMessageFormat,
        #[error("Empty message array")]
        /// Received an empty top-level MessagePack-RPC message array.
        EmptyMessageArray,
        #[error("Invalid message type: {0}")]
        /// Received a message with an invalid type tag.
        InvalidMessageType(u64),
        #[error("Invalid {kind} message length")]
        /// Received a message body with an unexpected number of fields.
        InvalidMessageLength {
            /// The message kind whose field count was invalid.
            kind: &'static str,
        },
        #[error("Invalid {kind} {field}")]
        /// Received a message field that did not have the expected shape or type.
        InvalidMessageField {
            /// The message kind or decode context.
            kind: &'static str,
            /// The field whose value was invalid.
            field: &'static str,
        },
        #[error("Depth limit exceeded")]
        /// A full MessagePack value exceeded the configured nesting limit.
        DepthLimitExceeded,
        #[error("No listener configured")]
        /// A caller requested a bound socket address before any listener was
        /// configured.
        ListenerNotConfigured,
        #[error("Listener has no SocketAddr")]
        /// A configured listener does not expose a bound `SocketAddr`.
        MissingSocketAddr,
        #[error("Expected exactly one parameter")]
        /// A MessagePack-RPC single-parameter helper received the wrong arity.
        ExpectedSingleParameter,
        #[error("Resource already taken: {resource}")]
        /// A single-consumer resource was taken more than once.
        ResourceAlreadyTaken {
            /// The resource that was already taken.
            resource: &'static str,
        },
        #[error("Task '{task}' failed: {source}")]
        /// A background task failed before completing normally.
        TaskFailed {
            /// The task that failed.
            task: &'static str,
            #[source]
            /// The underlying join failure.
            source: tokio::task::JoinError,
        },
        #[error("Unexpected response id: {id}")]
        /// Received a response for a request id that has no pending waiter.
        UnexpectedResponse {
            /// The request id.
            id: u32,
        },
        #[error("Malformed message: {0}")]
        /// Received a message that does not match the expected structure.
        MalformedMessage(String),
    }

    /// A type alias for `Result` with [`RpcError`] as the error type.
    pub type Result<T> = result::Result<T, RpcError>;

    /// Errors that can occur during RPC operations.
    pub enum RpcError {
        #[error("I/O error: {0}")]
        /// Error occurred during I/O operations.
        Io(io::Error),
        #[error("Connection failed: {source}")]
        /// Error occurred while trying to establish a connection.
        Connect {
            #[source]
            /// Underlying I/O error.
            source: io::Error,
        },
        #[error("Serialization error: {0}")]
        /// Error occurred during MessagePack serialization.
        Serialization(rmpv::encode::Error),
        #[error("Deserialization error: {0}")]
        /// Error occurred during MessagePack deserialization.
        Deserialization(rmpv::decode::Error),
        #[error(transparent)]
        /// Error related to the MessagePack-RPC protocol.
        Protocol(ProtocolError),
        #[error("Service error: {0}")]
        /// Error returned by the RPC service implementation.
        Service(ServiceError),
        #[error("Connection disconnected")]
        /// The connection was closed.
        Disconnect {
            #[source]
            /// Underlying I/O error, when available.
            source: Option<io::Error>,
        },
    }

    /// An error that occurred during the execution of an RPC service method.
    ///
    /// It consists of a name, which identifies the type of error, and a value,
    /// which can contain additional error details. This error type is used to
    /// convey service-specific errors back to the client. When sent over the RPC
    /// protocol, this error will be serialized into a map with "name" and "value"
    /// keys.
    pub struct ServiceError {
        /// The error type name.
        pub name: String,
        /// Additional error data.
        pub value: rmpv::Value,
    }

    /// Represents the different types of RPC messages: requests, responses, and
    /// notifications.
    pub enum Message {
        /// An RPC request.
        Request(Request),
        /// An RPC response.
        Response(Response),
        /// An RPC notification.
        Notification(Notification),
    }

    /// An RPC notification message containing a method name and parameters.
    pub struct Notification {
        /// The method name to invoke.
        pub method: String,
        /// Arguments to pass to the method.
        pub params: Vec<rmpv::Value>,
    }

    /// An RPC request message containing an ID, method name, and parameters.
    pub struct Request {
        /// Unique identifier for matching responses.
        pub id: u32,
        /// The method name to invoke.
        pub method: String,
        /// Arguments to pass to the method.
        pub params: Vec<rmpv::Value>,
    }

    /// An RPC response message containing an ID and either a result or an error.
    pub struct Response {
        /// Matches the request ID this is responding to.
        pub id: u32,
        /// The result value or error value.
        pub result: result::Result<rmpv::Value, rmpv::Value>,
    }

    /// RPC client for connecting to a server over TCP or Unix domain sockets.
    pub struct Client {}

    /// RPC server that can listen on TCP or Unix domain sockets.
    ///
    /// The connection type must implement [`Connection`]. A new connection instance
    /// is created for each accepted stream.
    pub struct Server<T>
    where
        T: Connection, {}

    /// A handle for controlling a running server.
    pub struct ServerHandle {}

    /// A listener that yields bidirectional streams.
    pub trait Listener: 'static + Send + Sync {
        /// Accept the next connection.
        fn accept<'life0, 'async_trait>(
            &self,
        ) -> ::core::pin::Pin<
            Box<
                dyn ::core::future::Future<Output = Result<Self::Stream>>
                    + ::core::marker::Send
                    + 'async_trait,
            >,
        >
        where
            'life0: 'async_trait,
            Self: 'async_trait;

        /// The stream type produced by accepting a connection.
        type Stream: 'static + AsyncRead + AsyncWrite + Send + Unpin;
    }

    /// Create a pair of connected in-memory streams.
    pub fn duplex(buffer_size: usize) -> (tokio::io::DuplexStream, tokio::io::DuplexStream) {}

    /// Shared runtime state for a live connection handler.
    ///
    /// This bundles the handler task inputs so transport code can start a client
    /// or accepted server connection without depending on lower-level connection
    /// plumbing types.
    pub struct ConnectionRuntime<S, T: Connection>
    where
        S: 'static + AsyncRead + AsyncWrite + Send + Unpin, {}

    /// Handle to an in-flight RPC request.
    ///
    /// Exposes the msgpack-RPC [`msgid`](Self::id) assigned to the request as
    /// soon as it is queued, so callers can reference it in out-of-band
    /// protocol messages (such as application-level cancellation) before the
    /// response arrives. The response is retrieved via
    /// [`response`](Self::response).
    pub struct RequestHandle {}

    /// The interface for sending RPC requests and notifications.
    pub struct RpcSender {}

    pub use rmpv::Value;
    /// A single Connection in an RPC server or client. For server connections, a
    /// new instance of the Connection is created for each incoming connection. For
    /// clients, a single instance is used for the lifetime of the connection.
    ///
    /// As a convenience for clients that don't need to handle requests or
    /// responses, the `Connection` trait is implemented for `()`, and the `Client`
    /// type exposes `send_request` and `send_notification` directly.
    ///
    /// Use the `#[async_trait]` attribute from the `async_trait` crate when
    /// implementing this trait to support async methods.
    pub trait Connection: 'static + Send + Sync {
        /// Called after a connection is initiated, either by a `Client` connecting
        /// outbound, or an incoming connection on a listening `Server`.
        fn connected<'life0, 'async_trait>(
            &self,
            _client: RpcSender,
        ) -> ::core::pin::Pin<
            Box<
                dyn ::core::future::Future<Output = Result<()>>
                    + ::core::marker::Send
                    + 'async_trait,
            >,
        >
        where
            'life0: 'async_trait,
            Self: 'async_trait, {
        }

        /// Handles an incoming RPC notification.
        ///
        /// By default, logs a warning about the unhandled notification.
        fn handle_notification<'life0, 'life1, 'async_trait>(
            &self,
            _client: RpcSender,
            method: &'life1 str,
            params: Vec<Value>,
        ) -> ::core::pin::Pin<
            Box<
                dyn ::core::future::Future<Output = Result<()>>
                    + ::core::marker::Send
                    + 'async_trait,
            >,
        >
        where
            'life0: 'async_trait,
            'life1: 'async_trait,
            Self: 'async_trait, {
        }

        /// Handles an incoming RPC request.
        ///
        /// By default, returns a `MethodNotFound` service error.
        fn handle_request<'life0, 'life1, 'async_trait>(
            &self,
            _client: RpcSender,
            method: &'life1 str,
            params: Vec<Value>,
        ) -> ::core::pin::Pin<
            Box<
                dyn ::core::future::Future<Output = Result<Value>>
                    + ::core::marker::Send
                    + 'async_trait,
            >,
        >
        where
            'life0: 'async_trait,
            'life1: 'async_trait,
            Self: 'async_trait, {
        }
    }

    /// A trait for creating connections.
    ///
    /// `ConnectionMaker` provides a generic way to create objects that implement
    /// the `Connection` trait. It is automatically implemented for any type that
    /// implements both `Connection` and `Default`.
    ///
    /// The ConnectionMaker is used to create a new Connection object for each
    /// incoming connection.
    pub trait ConnectionMaker<T>: Send + Sync
    where
        T: Connection, {
        /// Creates a new connection instance.
        fn make_connection(&self) -> T;
    }

    impl Client {
        /// Creates a new client connected to a TCP address.
        pub async fn connect_tcp<T>(addr: &str, service: T) -> Result<Self>
        where
            T: Connection, {
        }

        /// Creates a new client connected to a Unix domain socket.
        pub async fn connect_unix<P, T>(path: P, service: T) -> Result<Self>
        where
            P: AsRef<Path>,
            T: Connection, {
        }

        /// Creates a new client from any bidirectional stream.
        pub async fn from_stream<S, T>(stream: S, service: T) -> Result<Self>
        where
            S: 'static + AsyncRead + AsyncWrite + Send + Unpin,
            T: Connection, {
        }

        /// Queues an RPC request and returns a handle with the assigned msgid.
        pub async fn start_request(&self, method: &str, params: &[Value]) -> Result<RequestHandle> {
        }

        /// Returns a sender for issuing RPC requests and notifications.
        pub fn sender(&self) -> RpcSender {}

        /// Sends an RPC notification to the server. Convenience method for
        /// `RpcSender::send_notification`.
        pub async fn send_notification(&self, method: &str, params: &[Value]) -> Result<()> {}

        /// Sends an RPC request to the server. Convenience method for
        /// `RpcSender::send_request`.
        pub async fn send_request(&self, method: &str, params: &[Value]) -> Result<Value> {}

        /// Shuts down the client and waits for the handler task to complete.
        pub async fn close(self) -> Result<()> {}

        /// Signals the client to stop processing messages and close the connection.
        pub fn shutdown(&self) {}

        /// Waits for the client handler task to complete.
        pub async fn join(self) -> Result<()> {}
    }

    impl Debug for Client {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Drop for Client {
        fn drop(&mut self) {}
    }

    impl Clone for Message {
        fn clone(&self) -> Message {}
    }

    impl Debug for Message {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Message {
        /// Converts the message to a MessagePack-RPC compatible Value.
        pub fn to_value(&self) -> Value {}

        /// Creates a Message from a MessagePack-RPC compatible Value.
        pub fn from_value(value: Value) -> Result<Self> {}

        /// Encodes the message to MessagePack format and writes it to the given
        /// writer.
        pub fn encode<W: Write>(&self, writer: &mut W) -> Result<()> {}

        /// Reads and decodes a message from MessagePack format using the given
        /// reader.
        pub fn decode<R: Read>(reader: &mut R) -> Result<Self> {}
    }

    impl PartialEq for Message {
        fn eq(&self, other: &Message) -> bool {}
    }

    impl Clone for Notification {
        fn clone(&self) -> Notification {}
    }

    impl Debug for Notification {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for Notification {
        fn eq(&self, other: &Notification) -> bool {}
    }

    impl Clone for Request {
        fn clone(&self) -> Request {}
    }

    impl Debug for Request {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for Request {
        fn eq(&self, other: &Request) -> bool {}
    }

    impl Clone for Response {
        fn clone(&self) -> Response {}
    }

    impl Debug for Response {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for Response {
        fn eq(&self, other: &Response) -> bool {}
    }

    impl Clone for RpcSender {
        fn clone(&self) -> RpcSender {}
    }

    impl Debug for RpcSender {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl RpcSender {
        /// Queues an RPC request and returns a [`RequestHandle`] that carries
        /// the assigned `msgid` and yields the response when awaited. The
        /// method returns as soon as the request is accepted by the channel,
        /// so callers see the id before the response arrives.
        pub async fn start_request(&self, method: &str, params: &[Value]) -> Result<RequestHandle> {
        }

        /// Sends an RPC notification without waiting for a response.
        pub async fn send_notification(&self, method: &str, params: &[Value]) -> Result<()> {}

        /// Sends an RPC request and waits for the response. Equivalent to
        /// [`start_request`](Self::start_request) followed by awaiting the
        /// returned handle; the id is not exposed.
        pub async fn send_request(&self, method: &str, params: &[Value]) -> Result<Value> {}
    }

    impl Debug for ProtocolError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Display for ProtocolError {
        fn fmt(&self, __formatter: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {}
    }

    impl Error for ProtocolError {
        fn source(
            &self,
        ) -> ::core::option::Option<&(dyn ::thiserror::__private18::Error + 'static)> {
        }
    }

    impl From<&str> for ProtocolError {
        fn from(message: &str) -> Self {}
    }

    impl From<ProtocolError> for RpcError {
        fn from(source: ProtocolError) -> Self {}
    }

    impl From<String> for ProtocolError {
        fn from(message: String) -> Self {}
    }

    impl Debug for RequestHandle {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl RequestHandle {
        /// Awaits the response. Consumes the handle.
        pub async fn response(self) -> Result<Value> {}

        /// Returns the msgpack-RPC `msgid` of the request.
        pub fn id(&self) -> u32 {}
    }

    impl Debug for RpcError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Display for RpcError {
        fn fmt(&self, __formatter: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {}
    }

    impl Error for RpcError {
        fn source(
            &self,
        ) -> ::core::option::Option<&(dyn ::thiserror::__private18::Error + 'static)> {
        }
    }

    impl From<Error> for RpcError {
        fn from(error: io::Error) -> Self {}
    }

    impl From<Error> for RpcError {
        fn from(source: RmpvDecodeError) -> Self {}
    }

    impl From<ProtocolError> for RpcError {
        fn from(source: ProtocolError) -> Self {}
    }

    impl From<ValueWriteError> for RpcError {
        fn from(source: RmpvEncodeError) -> Self {}
    }

    impl Debug for ServerHandle {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl ServerHandle {
        /// Returns the bound TCP address of the server.
        ///
        /// This is only valid for TCP listeners; Unix listeners do not have a
        /// `SocketAddr`.
        pub fn local_addr(&self) -> Result<SocketAddr> {}

        /// Signals the server to stop accepting new connections.
        pub fn shutdown(&self) {}

        /// Waits for the server to stop and returns any error.
        pub async fn join(self) -> Result<()> {}
    }

    impl Debug for ServiceError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Display for ServiceError {
        fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {}
    }

    impl From<ServiceError> for rmpv::Value {
        fn from(error: ServiceError) -> Self {}
    }

    impl ServiceError {
        /// Creates a standard service error for an unknown RPC method.
        pub fn method_not_found(method: &str) -> Self {}
    }

    impl TryFrom<Value> for ServiceError {
        fn try_from(value: Value) -> result::Result<Self, Self::Error> {}

        type Error = Value;
    }

    impl<S, T> ConnectionRuntime<S, T>
    where
        S: 'static + AsyncRead + AsyncWrite + Send + Unpin,
        T: Connection,
    {
        /// Creates a runtime from a bidirectional stream and connection service.
        pub fn new(stream: S, service: T) -> Self {}

        /// Returns a sender for issuing RPC requests and notifications.
        pub fn sender(&self) -> RpcSender {}

        /// Returns a shutdown handle for the background reader task.
        pub fn shutdown_sender(&self) -> watch::Sender<bool> {}

        /// Runs the connection handler until the stream closes or shutdown is
        /// requested.
        pub async fn run(self) -> Result<()> {}
    }

    impl<T> Server<T>
    where
        T: Connection + Default,
    {
        /// Creates a new server from a listener using `T::default` for each
        /// connection.
        pub fn from_listener<L>(listener: L) -> Result<Self>
        where
            L: Listener, {
        }
    }

    impl<T> Server<T>
    where
        T: Connection,
    {
        /// Configures the server to accept connections from a custom listener.
        pub fn with_listener<L>(self, listener: L) -> Result<Self>
        where
            L: Listener, {
        }

        /// Configures the server to listen on a TCP address.
        pub async fn tcp(self, addr: &str) -> Result<Self> {}

        /// Configures the server to listen on a Unix domain socket.
        pub async fn unix<P: AsRef<Path>>(self, path: P) -> Result<Self> {}

        /// Creates a new Server with the given ConnectionMaker.
        pub fn from_maker<M>(maker: M) -> Self
        where
            M: 'static + ConnectionMaker<T> + Send + Sync, {
        }

        /// Helper method to create a Server from a closure
        pub fn from_fn<F>(f: F) -> Self
        where
            F: 'static + Fn() -> T + Send + Sync, {
        }

        /// Returns the bound address of the server. Only valid for TCP listeners
        /// that have already been bound, otherwise returns an error.
        pub fn local_addr(&self) -> Result<SocketAddr> {}

        /// Starts the server and begins accepting connections.
        pub async fn run(self) -> Result<()> {}

        /// Starts the server and returns a handle for lifecycle control.
        pub async fn spawn(self) -> Result<ServerHandle> {}
    }
}
